<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ExportController extends \Illuminate\Routing\Controller
{
    /** Allowed output formats. The "md" alias is normalized to "markdown". */
    private array $formats = ['pdf', 'markdown', 'md', 'json', 'csv'];

    /** Allowed export scopes. */
    private array $types = ['full', 'issues', 'reports'];

    /** Default MIME types per format. */
    private array $mimeMap = [
        'json'     => 'application/json',
        'markdown' => 'text/markdown',
        'csv'      => 'text/csv',
        'pdf'      => 'application/pdf',
    ];

    /**
     * Resolve the authenticated user.
     *
     * Tries `auth('api')->user()` first (spec requirement) and falls back to
     * the ApiAuthMiddleware request attribute `auth_user`.
     */
    private function authUser(Request $request): ?array
    {
        $u = auth('api')->user();
        if ($u) {
            return is_object($u) ? (array) $u : $u;
        }
        return $request->get('auth_user');
    }

    /* -----------------------------------------------------------------
     |  Persistence (mirrors ProjectController)
     | -----------------------------------------------------------------*/

    private function userPath(int $userId): string
    {
        return base_path("database/uizard/user_{$userId}.json");
    }

    private function loadData(int $userId): array
    {
        $path = $this->userPath($userId);
        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }
        if (!file_exists($path)) {
            file_put_contents($path, json_encode(['projects' => []]));
        }
        $data = json_decode(file_get_contents($path), true);
        return is_array($data) ? $data : ['projects' => []];
    }

    private function findProject(array $data, string $projectId): ?array
    {
        foreach ($data['projects'] ?? [] as $p) {
            if ((string) ($p['id'] ?? '') === $projectId) {
                return $p;
            }
        }
        return null;
    }

    /* -----------------------------------------------------------------
     |  Endpoint
     | -----------------------------------------------------------------*/

    /**
     * POST /api/exports
     *
     * Body:
     *   - project_id (required, string)
     *   - format     (required, in: pdf|markdown|json|csv)
     *   - type       (required, in: full|issues|reports)
     *
     * For markdown / json / csv the file is generated on disk and its
     * path returned. For pdf a mock file path is returned with a flag
     * indicating it is a queued / mock export.
     */
    public function export(Request $request): \Illuminate\Http\JsonResponse
    {
        $user = $this->authUser($request);
        if (!$user) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }

        $v = Validator::make($request->all(), [
            'project_id' => 'required|string',
            'format'     => 'required|string|in:' . implode(',', $this->formats),
            'type'       => 'required|string|in:' . implode(',', $this->types),
        ]);
        if ($v->fails()) {
            return response()->json(['error' => $v->errors()->first()], 422);
        }

        $projectId = (string) $request->input('project_id');
        $format    = strtolower((string) $request->input('format'));
        $type      = (string) $request->input('type');

        if ($format === 'md') {
            $format = 'markdown';
        }

        $data = $this->loadData((int) $user['id']);
        $project = $this->findProject($data, $projectId);
        if (!$project) {
            return response()->json(['error' => 'Project not found'], 404);
        }

        $payload = $this->buildPayload($project, $type, $format, (int) $user['id']);

        if ($format === 'pdf') {
            return response()->json([
                'success' => true,
                'data'    => [
                    'format'        => 'pdf',
                    'type'          => $type,
                    'project_id'    => $projectId,
                    'file_path'     => 'storage/app/exports/project_' . $projectId . '_' . $type . '.pdf',
                    'absolute_path' => storage_path('app/exports/project_' . $projectId . '_' . $type . '.pdf'),
                    'mock'          => true,
                    'message'       => 'PDF export queued. File will be generated by the background PDF worker.',
                    'preview'       => [
                        'reply'  => 'PDF generation is mocked in this build. The payload below would be rendered into the document.',
                        'format' => 'pdf',
                        'type'   => $type,
                    ],
                    'payload_summary' => [
                        'project_name'   => $project['name'] ?? 'Untitled',
                        'screen_count'   => count($payload['screens'] ?? []),
                        'annotation_count' => count($payload['annotations'] ?? []),
                        'exported_at'    => $payload['exported_at'] ?? date('Y-m-d H:i:s'),
                    ],
                ],
            ]);
        }

        return response()->json([
            'success' => true,
            'data'    => $this->writeExportFile($projectId, $type, $format, $payload),
        ]);
    }

    /* -----------------------------------------------------------------
     |  File generation
     | -----------------------------------------------------------------*/

    /**
     * Write the export payload to disk in the requested format and return
     * a descriptor suitable for the API response.
     */
    private function writeExportFile(string $projectId, string $type, string $format, array $payload): array
    {
        $dir = storage_path('app/exports');
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $ts   = date('Ymd_His');
        $base = "project_{$projectId}_{$type}_{$ts}";
        $filename = '';
        $mime     = $this->mimeMap[$format] ?? 'application/octet-stream';
        $body     = '';

        switch ($format) {
            case 'json':
                $filename = "{$base}.json";
                $body = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                break;

            case 'markdown':
                $filename = "{$base}.md";
                $body = $this->toMarkdown($payload, $type);
                break;

            case 'csv':
                $filename = "{$base}.csv";
                $body = $this->toCsv($payload, $type);
                break;

            default:
                // Should not happen: validated above.
                $filename = "{$base}.txt";
                $body = '';
                break;
        }

        $absolute = $dir . DIRECTORY_SEPARATOR . $filename;
        file_put_contents($absolute, $body);

        return [
            'format'       => $format,
            'type'         => $type,
            'project_id'   => $projectId,
            'file_path'    => 'storage/app/exports/' . $filename,
            'file_name'    => $filename,
            'absolute_path' => $absolute,
            'mime'         => $mime,
            'size'         => filesize($absolute) ?: 0,
            'download_url' => url('storage/app/exports/' . $filename),
            'exported_at'  => $payload['exported_at'] ?? date('Y-m-d H:i:s'),
        ];
    }

    /**
     * Build the normalized export payload. The `type` flag controls which
     * sections are included: full (everything), issues (annotations + AI
     * detected issues), reports (project + screens summary).
     */
    private function buildPayload(array $project, string $type, string $format, int $userId): array
    {
        $projectInfo = [
            'id'           => $project['id'] ?? null,
            'name'         => $project['name'] ?? 'Untitled',
            'description'  => $project['description'] ?? '',
            'industry'     => $project['industry'] ?? null,
            'product_type' => $project['product_type'] ?? null,
            'design_style' => $project['design_style'] ?? null,
            'created_at'   => $project['created_at'] ?? null,
            'updated_at'   => $project['updated_at'] ?? null,
            'user_id'      => $userId,
        ];

        $screens = array_map(fn($s) => [
            'id'         => $s['id'] ?? null,
            'name'       => $s['name'] ?? null,
            'width'      => $s['width'] ?? null,
            'height'     => $s['height'] ?? null,
            'background' => $s['background'] ?? null,
            'element_count' => is_array($s['elements'] ?? null) ? count($s['elements']) : 0,
            'hotspot_count' => is_array($s['hotspots'] ?? null) ? count($s['hotspots']) : 0,
            'created_at' => $s['created_at'] ?? null,
            'updated_at' => $s['updated_at'] ?? null,
        ], $project['screens'] ?? []);

        $payload = [
            'project'     => $projectInfo,
            'screens'     => $screens,
            'annotations' => [],
            'issues'      => [],
            'reports'     => [],
            'type'        => $type,
            'format'      => $format,
            'exported_at' => date('Y-m-d H:i:s'),
            'generator'   => 'UI Inspectore Export Service 1.0',
        ];

        if ($type === 'full' || $type === 'issues') {
            // Per-project annotations live in the user file. For the export
            // we expose an empty array here; the projects array on the user
            // file doesn't currently scope annotations per project. This is
            // a stable shape that callers can rely on.
            $payload['annotations'] = [];
            $payload['issues']      = [];
        }

        if ($type === 'full' || $type === 'reports') {
            $payload['reports'] = [
                'summary' => [
                    'screen_count'      => count($screens),
                    'total_elements'    => array_sum(array_map(fn($s) => $s['element_count'] ?? 0, $screens)),
                    'total_hotspots'    => array_sum(array_map(fn($s) => $s['hotspot_count'] ?? 0, $screens)),
                    'avg_screen_width'  => count($screens) > 0 ? (int) round(array_sum(array_map(fn($s) => (int) ($s['width'] ?? 0), $screens)) / count($screens)) : 0,
                    'avg_screen_height' => count($screens) > 0 ? (int) round(array_sum(array_map(fn($s) => (int) ($s['height'] ?? 0), $screens)) / count($screens)) : 0,
                ],
            ];
        }

        return $payload;
    }

    /**
     * Render the payload as a Markdown document.
     */
    private function toMarkdown(array $payload, string $type): string
    {
        $p    = $payload['project'];
        $now  = $payload['exported_at'];
        $name = $p['name'] ?? 'Project';

        $md  = [];
        $md[] = "# {$name}";
        $md[] = "";
        if (!empty($p['description'])) {
            $md[] = $p['description'];
            $md[] = "";
        }
        $md[] = "- **Project ID:** `{$p['id']}`";
        $md[] = "- **Type:** `{$type}`";
        $md[] = "- **Industry:** " . ($p['industry'] ?? '-');
        $md[] = "- **Product Type:** " . ($p['product_type'] ?? '-');
        $md[] = "- **Design Style:** " . ($p['design_style'] ?? '-');
        $md[] = "- **Created:** " . ($p['created_at'] ?? '-');
        $md[] = "- **Updated:** " . ($p['updated_at'] ?? '-');
        $md[] = "- **Exported:** {$now}";
        $md[] = "";

        if (!empty($payload['reports']['summary'])) {
            $s = $payload['reports']['summary'];
            $md[] = "## Report Summary";
            $md[] = "";
            $md[] = "| Metric | Value |";
            $md[] = "|--------|------:|";
            $md[] = "| Screens | " . ($s['screen_count'] ?? 0) . " |";
            $md[] = "| Total Elements | " . ($s['total_elements'] ?? 0) . " |";
            $md[] = "| Total Hotspots | " . ($s['total_hotspots'] ?? 0) . " |";
            $md[] = "| Avg Width | " . ($s['avg_screen_width'] ?? 0) . " |";
            $md[] = "| Avg Height | " . ($s['avg_screen_height'] ?? 0) . " |";
            $md[] = "";
        }

        $md[] = "## Screens";
        $md[] = "";
        if (empty($payload['screens'])) {
            $md[] = "_No screens in this project._";
        } else {
            $md[] = "| # | ID | Name | Width | Height | Elements | Hotspots |";
            $md[] = "|---|----|------|------:|-------:|---------:|---------:|";
            foreach ($payload['screens'] as $i => $s) {
                $md[] = '| ' . ($i + 1)
                    . ' | `' . ($s['id'] ?? '-') . '`'
                    . ' | ' . ($s['name'] ?? '-')
                    . ' | ' . ($s['width'] ?? '-')
                    . ' | ' . ($s['height'] ?? '-')
                    . ' | ' . ($s['element_count'] ?? 0)
                    . ' | ' . ($s['hotspot_count'] ?? 0)
                    . ' |';
            }
        }
        $md[] = "";
        $md[] = "---";
        $md[] = "_Generated by UI Inspectore on {$now}._";

        return implode("\n", $md);
    }

    /**
     * Render the payload as a CSV document.
     */
    private function toCsv(array $payload, string $type): string
    {
        $fh = fopen('php://temp', 'r+');
        if ($fh === false) {
            return '';
        }

        // Header / metadata rows.
        fputcsv($fh, ['key', 'value']);
        fputcsv($fh, ['project_id',   $payload['project']['id'] ?? '']);
        fputcsv($fh, ['project_name', $payload['project']['name'] ?? '']);
        fputcsv($fh, ['industry',     (string) ($payload['project']['industry'] ?? '')]);
        fputcsv($fh, ['product_type', (string) ($payload['project']['product_type'] ?? '')]);
        fputcsv($fh, ['design_style', (string) ($payload['project']['design_style'] ?? '')]);
        fputcsv($fh, ['export_type',  $type]);
        fputcsv($fh, ['exported_at',  $payload['exported_at'] ?? '']);
        fputcsv($fh, []);

        fputcsv($fh, ['screen_index', 'screen_id', 'screen_name', 'width', 'height', 'element_count', 'hotspot_count']);
        if (empty($payload['screens'])) {
            fputcsv($fh, ['', '', '', '', '', '', '']);
        } else {
            foreach ($payload['screens'] as $i => $s) {
                fputcsv($fh, [
                    $i + 1,
                    $s['id'] ?? '',
                    $s['name'] ?? '',
                    $s['width'] ?? '',
                    $s['height'] ?? '',
                    $s['element_count'] ?? 0,
                    $s['hotspot_count'] ?? 0,
                ]);
            }
        }

        rewind($fh);
        $csv = stream_get_contents($fh);
        fclose($fh);

        return (string) $csv;
    }
}
